pipeline {
    agent any

    environment {
        IMAGE_NAME = 'hello-world-app'
        TAG = "${env.BUILD_NUMBER}"
    }

    triggers {
        pollSCM('* * * * *') // or use GitHub webhook for push trigger
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/NoorbabaShaik/express.git', branch: 'master'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t $IMAGE_NAME:$TAG .'
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    sh 'node test.js'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed.'
        }
        failure {
            echo 'Build or test failed!'
        }
    }
}
