pipeline {
    agent any

    environment {
        IMAGE_NAME = "hello-world"
        DOCKER_TAG = "latest"
    }

    triggers {
        githubPush()
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-creds',
                    url:'https://github.com/NoorbabaShaik/express.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t $IMAGE_NAME:$DOCKER_TAG .'
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    sh 'echo "Running tests... All tests passed!"'
                }
            }
        }
    }
}
